sequenceDiagram
  participant c as System A
  participant tak as Tjänstekatalog
  participant as as Auktorisationstjänst
  participant f as Federationsmedlemskatalog
  participant rs as System B

  c ->>+ tak: Sök e-tjänst, givet logisk adressat <br/> och interoperabilitetsspecifikation
  tak -->>- c: e-tjänstens URL, Auktorisationstjänstens URL

  c ->>+ as: Begär åtkomst till e-tjänsten. <br/>Skicka med System A:s klientidentitet
  as ->>+ f: inhämta federationsmedlemsinformation <br/> för e-tjänsten
  f -->>- as: federationsmedlemsdata
  as ->> as: Utvärdera åtkomstpolicy för System A 
  alt Åtkomst beviljad
    as -->> c: åtkomstintyg
  else Access Denied 
    as -->>- c: HTTP 403 Forbidden
  end 

  c ->>+ rs: Anropa e-tjänst hos System B

  rs ->> rs: Validera åtkomstintyg
  alt åtkomstintyg giltigt
    rs ->> rs: utför begäran
    rs -->> c: resultat
  else åtkomstintyg ogiltigt
    rs -->>- c: HTTP 403 Forbidden
  end
