erDiagram
%%{init: {'theme':'forest'}}%%
INFORMATION_FEDERATION_OPERATOR }|--|{ INFORMATION_FEDERATION : "controls"
INFORMATION_FEDERATION }|--|{ INFORMATION_FEDERATION_MEMBER : "member"
INFORMATION_FEDERATION ||--|{ INTEROPERABILITY_SPECIFICATION: "refers to"
INTEROPERABILITY_SPECIFICATION ||--|{ API_SPECIFICATION: "refers to"
ORGANISATION }|--|| INFORMATION_FEDERATION_MEMBER: "is"
INFORMATION_FEDERATION_MEMBER ||--|| ORGANISATION_METADATA: "described by"
INFORMATION_FEDERATION_MEMBER }|--|{ INFORMATION_FEDERATION_ROLE: "can take"



ORGANISATION_METADATA }|--|| ORGANISATION: "described by"
ORGANISATION_METADATA }|--|| INFORMATION_FEDERATION_MEMBER_CATALOG: "is listed in"
INFORMATION_FEDERATION_ROLE ||--|| PRODUCER_ROLE: "can be"
INFORMATION_FEDERATION_ROLE ||--|| CLIENT_ROLE: "can be"

PRODUCER_ROLE ||--|{API: "uses"
CLIENT_ROLE ||--|{API_CLIENT: "uses"
API ||--|| API_METADATA: "described by"
API_CLIENT ||--|| API_CLIENT_METADATA : "described by"
API_METADATA ||--|{API_CATALOG: "registered in"
API_CLIENT_METADATA ||--|{ INFORMATION_FEDERATION_MEMBER_CATALOG:"registered in"

API_CLIENT ||--|{API_CATALOG : "uses"
API ||--|{ AUTHORISATION_SERVICE: "refers to"
API_CLIENT ||--|{ AUTHORISATION_SERVICE: "calls"
API_CLIENT ||--|| DIGTIAL_IDENTITY :"has"
AUTHORISATION_SERVICE ||--|{ CERTIFICATE_AUTHORITY: "trusts"
INFORMATION_FEDERATION ||--|{ CERTIFICATE_AUTHORITY: "decides"
CERTIFICATE_AUTHORITY ||--|{ CERTIFICATE : "issues"


AUTHORISATION_SERVICE ||--|| AUTHORISATION_TOKEN : "issues"
DIGTIAL_IDENTITY||--|{CERTIFICATE: "is represented by"
AUTHORISATION_TOKEN ||--|| API_CLIENT : "is issued to"
AUTHORISATION_TOKEN ||--|| API: "grants access to"

