erDiagram
%%{init: {'theme':'forest'}}%%


ORGANISATION }|--|| INFORMATION_FEDERATION_MEMBER: "is"
INFORMATION_FEDERATION_MEMBER }|--|{ INFORMATION_FEDERATION_ROLE: "can take"
INFORMATION_FEDERATION_MEMBER }|--|{ INFORMATION_FEDERATION_MEMBER_CATALOG: "listed in"
INFORMATION_FEDERATION_ROLE ||--|{ CLIENT_ROLE: "can be"
CLIENT_ROLE ||--|{API_CLIENT: "uses"
API_CLIENT ||--|| API_CLIENT_METADATA : "described by"
API_CLIENT_METADATA ||--|| DIGTIAL_IDENTITY :"descripes"
%%DIGTIAL_IDENTITY||--|{CERTIFICATE: "is represented by"
%%CERTIFICATE ||--|| CERTIFICATE_AUTHORITY : "issued by"
API_CLIENT_METADATA ||--|{ INFORMATION_FEDERATION_MEMBER_CATALOG:"registered in"
INFORMATION_FEDERATION_ROLE ||--|{ PRODUCER_ROLE: "can be"
PRODUCER_ROLE ||--|{API: "supplies"
API ||--|| API_METADATA: "described by"
