sequenceDiagram
  box rgb(230, 240, 199) as Leverantör av <br/>API-klient
    participant c as API-klient
  end
  box rgb(242, 240,233) Federationsoperatören Inera
    participant tak as Tjänstekatalog
    participant ias as Auktorisationstjänst
    participant ia as Avtalsrepo
    %%actor fu as Federationsoperatör
    %%participant f as Federationsmedlemskatalog
  end
  box rgb(256, 240, 200) as Leverantör av<br/>digital tjänst via API
    participant as as Auktorisationstjänst
    participant rs as API
  end
  
  c ->>+ ias: Begär åtkomst till Tjänstekatalogen. <br/>Skicka med API-klientens
  ias ->>+ ia: Inhämta beslutsunderlag<br/>för åtkomstbeslut
  ia -->>- ias: avtalsinfo
  ias ->> ias: Utvärdera åtkomstpolicy<br/>för Tjänstekatalogen
  ias -->>- c: åtkomstintyg 

  
  c ->>+ tak: Sök API, givet<br/>logisk adressat och <br/> interoperabilitetsspecifikation
  tak ->> tak: validera åtkomstintyg
  tak -->>- c: APIets URL,<br/>Auktorisationstjänstens URL

