sequenceDiagram
  box rgb(230, 240, 199) as Leverantör av <br/>API-klient
    participant c as API-klient
  end
  box rgb(242, 240,233) Federationsoperatören Inera
    participant tak as Tjänstekatalog
    %%participant ias as Auktorisationstjänst
    participant ia as Avtalsrepo
    actor fu as Federationsoperatör
    participant f as Federationsmedlemskatalog
  end
  box rgb(256, 240, 200) as Leverantör av<br/>digital tjänst via API
    %%participant as as Auktorisationstjänst
    participant rs as API
  end



  activate fu
  rs -) fu: Skriv avtal om<br/>medlemsskap i<br/>informationsfederationen 
  fu -) ia: Registrera<br/>informationsfederationsavtal<br/>med Leverantör av<br/>digital tjänst via API
  fu -) f: Registrera Leverantör av<br/>digital tjänst via API<br/>i Federationsmedlemskatalogen
  fu -) tak: Registrera API<br/>i Tjänstekatalogen
  c -) fu: Skriv avtal om medlemsskap<br/>i informationsfederationen 
  fu -) ia: Registrera<br/>informationsfederationsavtal<br/>med Leverantör av API-klient
  fu -) f: Registrera Leverantör<br/>av API-klient, samt<br/>API-klientens metadata <br/>i Federationsmedlemskatalogen
  deactivate fu