sequenceDiagram
  box rgb(230, 240, 199) as Leverantör av API-klient
    participant c as API-klient
  end
  box rgb(242, 240,233) Federationsoperatören Inera
    participant tak as Ineras Tjänstekatalog
    participant ias as Ineras Auktorisationstjänst
    participant ia as Ineras Avtal
    actor fu as Federationsoperatör
    participant f as Ineras Federationsmedlemskatalog
  end
  box rgb(256, 240, 200) as Leverantör av digital tjänst via API
    participant as as Auktorisationstjänst
    participant rs as API
  end



  c ->>+ as: Begär åtkomst till API. <br/>Skicka med API-klientens identitet, och<br/>eventuell slutanvändares identitet
  
  as ->>+ ias: Begär åtkomst till Federationsmedlemskatalogen. <br/>Skicka med Auktorisationstjänstens identitet
  ias ->> ias: Utvärdera åtkomstpolicy för Federationsmedlemskatalogen
  ias -->>- as: åtkomstintyg
  
  as ->>+ f: inhämta federationsmedlemsinformation <br/> för e-tjänsten
  f ->> f: validera åtkomstintyg
  f -->>- as: federationsmedlemsdata
  
  as ->> as: Utvärdera åtkomstpolicy för API
  as -->>- c: åtkomstintyg
  
  c ->>+ rs: Anropa API
  rs ->> rs: validera åtkomstintyg
  rs ->> rs: utför begäran
  rs -->>- c: resultat
