erDiagram
%%{init: {'theme':'forest'}}%%

API_SPECIFICATION ||--|{ INTEROPERABILITY_SPECIFICATION : "refered by"
INTEROPERABILITY_SPECIFICATION ||--|| SERVICE: "defines"
ORGANISATION }|--|| INFORMATION_SYSTEM: "owns"
INFORMATION_SYSTEM ||--|{ API : "provides"

API ||--|| API_SPECIFICATION : "conforms with"
API ||--|{SERVICE : "can be part of"
API_METADATA ||--|{API_CATALOG: "registered in"

API_CLIENT ||--|{API_CATALOG : "uses"

API ||--|| API_METADATA: "described by"


API_SPECIFICATION {
string specificationId "unique identifier"
string name 
string version "the version of the specification"
string standardType "standard that the API conforms with (WSDL, OpenAPI etc)"
blob specification "the text (JSON,YAML) that describes the actual API"
}
API {
string name

}
API_METADATA {
string specificationId "reference to spec"
string api_id "the unique id for the API"
string[] INTEROPERABILITY_SPECIFICATION "one or more interoperability specs that is supported by the API"
string organisationName 
string organisationId "if of the owner of the API"
string logical_adress " the logical address for the API"
string technical_address "the url for the API"
string authority_service "the Auth service wher to get access tokens"
}

API_CATALOG {
string[] API_METADATA
}
INTEROPERABILITY_SPECIFICATION {
string name
string version
string specificationId "the unique id of the interop specification"
string shortDescription "short description of the INTEROPERABILITY_SPECIFICATION"
blob specification "the full specification in various formats"
string[] API_SPECIFICATION "reference to the API_SPECIFICATION(s) used in this specification"
}
ORGANISATION {
string name
string organisationId
}