erDiagram
%%{init: {'theme':'forest'}}%%

Samverkans_behov ||--|| Syfte :"kan ha"
Samverkans_behov ||--|| Informationsutbyte: "kan vara"

Informationsutbyte ||--|{ Digital_tjanst: "kan ske via"
Digital_tjanst ||--|{ API : "kan ha 1-*" 
API ||--|{ Digital_tjanst: "kan ingå i 1-*"
Resurs ||--|{ API: "tillhandahålls av"
Information ||--|| Resurs : "bärs av"

Informationsutbyte ||--|| Interoperabilitetsspecifikation :"beskrivs av"
Interoperabilitetsspecifikation ||--|{ API_SPECIFICATION: "referear till"
API_SPECIFICATION ||--|| API :" definerar"
