flowchart TB

subgraph serviceConsumer[Service Consumer]
    infoSys1(Information System)-->
    apiClient1(API client)
end
serviceConsumer:::system

subgraph serviceCatalog[Service Catalog]
    auth2(AuthorizationService)
    api2(API)
    api2-.trusts.->auth2
end
serviceCatalog:::system

subgraph serviceProducer[Service Producer]
    auth3(AuthorizationService)
    api3(API)
    api3-.trusts.->auth3
    
end
serviceProducer:::system

subgraph federationCatalog[Information Federation Membership Catalog]
    auth4(AuthorizationService)
    api4(API)
    api4-.trusts.->auth4
end
federationCatalog:::system

subgraph identityFederation[Identity & Authorization Federation]
    h5[&lt&ltFederation&gt&gt]:::type
    d5[A federation for \ntrust, digital identities, \nand federated authorization.]:::description
end
identityFederation:::system

apiClient1-- requests access --> auth2
apiClient1-- calls API --> api2
apiClient1-- requests access --> auth4
apiClient1-- calls API --> api4
apiClient1-- requests access --> auth3
apiClient1-- calls API --> api3
auth2 & auth3 & auth4 -. trusts.-> identityFederation
%% Element type definitions
classDef system fill:#D2B9D5
classDef type stroke-width:0px, color:#fff, fill:transparent, font-size:12px
classDef description stroke-width:0px, color:#fff, fill:transparent, font-size:13px
