erDiagram

"Federationsoperatör" ||--|{ "Informationsfederation" : "hanterar"
"Informationsfederation" ||--|| "Federationsavtal" : "regleras av"
"Federationsavtal" }|--|| "Federationsoperatör" : "är avtalspart"
"Informationsfederation" ||--|{ "Digital tjänst" : "omfattar"
"Digital tjänst" ||--|| "Interoperabilitetsspecifikation" : "beskrivs av"